mindersec/minder-rules-and-profiles

rule-types/github/dockerfile_no_latest_tag.yaml

Hello there! 
While testing the `Dockerfile no latest tag` rule, I ran into a little hiccup. It turns out the rule wasn't quite doing what we expected. After a bit of sleuthing, I discovered that removing the caret symbol at the end of the regex pattern did the trick. I also took a moment to tidy up some older comments in the code.
Thank you for providing us with this wonderful project! Cheers 🍻

Fix regex issue and typos in Dockerfile rule

---

rule-types/github/secret_push_protection.yaml
rule-types/github/secret_scanning.yaml

We might want to have a different pair of rules for github Pro users,
but I think it's mroe pressing to make the existing rules work for our
setup and having the rules seamlessly skip private repos would allow us
to use more rules across more repositories in the stacklok org.

Skip secret_push_protection and secret_scanning for private repos

---

profiles/github/profile.yaml
profiles/github/stacklok-profile-read-only.yaml
profiles/github/stacklok-profile-remediate.yaml
rule-types/github/automatic_branch_deletion.yaml

This rule checks whether automatic branch deletion is enabled or not [1].
This also adds the rule to our reference profiles.
[1] https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches

Add new rule-type that checks if automated branch deletion is enabled

---

rule-types/github/dockerfile_no_latest_tag.yaml

Hello again,
I have examined the documentation [here](https://docs.docker.com/engine/reference/builder/#from) to support the multi-stage structure in the Dockerfile. I created the necessary regex. When tested with the following images, it successfully filtered out those with no tag and 'latest'. I did not encounter any issues during testing.
| Image                                       | Matched  |
|-----------------------------------------------------|--------|
| FROM --platform=linux/amd64 golang@sha256:337543447173c2238c78d4851456760dcc57c1dfa8c3bcd94cbee8b0f7b32ad0 AS builder |        |
| FROM --platform=linux/amd64 golang AS builder            | ✔      |
| FROM --platform=linux/amd64 golang:latest AS builder     | ✔      |
| FROM …

Add multi-stage support for dockerfile rule

---

profiles/github/stacklok-profile-read-only.yaml
profiles/github/stacklok-profile-remediate.yaml

We still store some old artifact versions in the db and in github that are not
signed - by default minder stores up to 30 days worth of artifacts. At the
same time, we don't use any floating tag like latest so it's problematic
to pin a single tag.
Since the failure wouldn't tell us much, let's remove the rule for now.

Remove artifact_signature for the helm chart for now

---

profiles/github/stacklok-profile-read-only.yaml
profiles/github/stacklok-profile-remediate.yaml

We don't want those rules to fail for private repos

Skip private repos in stacklok profiles

---

rule-types/github/dockerfile_no_latest_tag.yaml

`FROM scratch` is a special case, we shouldn't flag it as using the
latest tag (unlike e.g. `FROM golang`)

Special-case FROM scratch when detecting the latest tag

---

rule-types/github/actions_check_pinned_tags.yaml

Defining the excludes ensures that the remediation can take that into
account in a definition. Also patches the evaluation so that excluded
actions don't cause the rule to fail.
Fixes: #25

Support excludes in actions_check_pinned_tags

---

profiles/github/stacklok-profile-read-only.yaml
profiles/github/stacklok-profile-remediate.yaml

Let's keep expanding the stacklok profile. Since this rule is also added
to the remediating profile, we'd get PRs as a result after applying this
profile.

Add actions_check_pinned_tags to the stacklok profiles

---

profiles/github/ghas.yaml

Added the dependabot_configured.yaml rule type to this example profile (for golang). I'm proposing we do this for completeness of the example profile and a docs page I'm working on to show how to use Minder with GHAS.

Update ghas.yaml example profile to include dependabot_configured rule type

---

rule-types/github/artifact_signature.yaml

The following updates the artifact_signature ruletype by:
* allow to setup a custom sigstore instance
* extend the available check one can configure from a profile
Motivated by https://github.com/stacklok/epics/issues/183

Update artifact_signature to allow for more provenance checks

---

rule-types/github/artifact_signature.yaml

Fix `artifact_signature` rule

---

rule-types/github/pr_trusty_check.yaml

This was changed in minder and we had forgotten to update it.

Fix trusty ruletype

---

rule-types/github/no_binaries_in_repo.yaml

This adds a new rule that checks that no binary artifacts are checked in
a github repo.

Add new rule to check for binary artifacts in repositories

---

profiles/github/artifacts/artifact-signature-extended.yaml
profiles/github/artifacts/artifact-signature-simple.yaml
profiles/github/profile.yaml
rule-types/github/artifact_signature.yaml

This renames the field so it's more generic since we'll allow in Minder to specify other types of identities, not just a workflow name.
It also adds 2 example profiles using the ruletype - a simple one and an extended version of it.
Related to: https://github.com/stacklok/minder/issues/2298

Rename the workflow_name to signer_identity for artifact_signature

---

rule-types/github/artifact_signature.yaml

We seem to have missed this attribute.

Add tag_regex to the artifact_signature schema

---

rule-types/github/pr_trusty_check.yaml
rule-types/github/pr_vulnerability_check.yaml

The following PR:
* updates the `pr_trusty_check` rule so it now enables the go support in Trusty
* points the Trusty instance to the production one.
* updates the `pr_vulnerability_check` rule so it uses go.mod instead of go.sum for parsing
Example use:
* https://github.com/rdimitrov/bad-repo-go/pull/19

Enable and fix Go support for the Trusty and OSV rule types

---

rule-types/github/homoglyphs_invisible_characters.yaml
rule-types/github/homoglyphs_mixed_scripts.yaml

The implications of homoglyphs type of attacks are described in https://github.com/stacklok/minder/issues/2121
It also contains additional explicatory links and useful examples.

Add homoglyphs rule types

---

rule-types/github/codeql_enabled.yaml

For some reason we were only setting up codeQL, but not actually running
it.

Fix codeQL remediation

---

rule-types/github/dependabot_configured.yaml

This removes the hardcoded `main` branch in favor of whatever the repo
selected as their default branch.

Use default branch for dependabot check

---

profiles/github/stacklok-health-check.yaml

This is a profile meant to verify the general overall health of an
organization in an easy way. It does not alert nor remediate by default.
Co-Authored-By: Radoslav Dimitrov <radoslav@stacklok.com>
Co-Authored-By: Teodor Yanev <teodor@stacklok.com>
Co-Authored-By: Eleftheria Stein-Kousathana <eleftheria@stacklok.com>
Co-Authored-By: Don Browne <dmjb@users.noreply.github.com>
Co-Authored-by: Adolfo Garcia Veytia (puerco) <puerco@stacklok.com>
Co-Authored-by: Evan Anderson <evan@stacklok.com>
Co-Authored-by: Brian Dussault <dussaultbrian@gmail.com>

Add profile for Stacklok health check

---

profiles/github/profile.yaml

This was causing the rule to always pass.

Fix actions_check_pinned_tags example in profile.yaml

---

.github/workflows/ensure-tests-for-all-rules.yml

Fixes https://github.com/stacklok/minder-smoke-tests/issues/84

Add a workflow that checks if all existing ruletypes have tests

---

rule-types/github/no_open_security_advisories.yaml

Please see https://stacklok.slack.com/archives/C057KR4DT0W/p1711998911156389 for details around the discussion. 
TL;DR: GitHub webhook events are not being sent when a draft GHSA is created. The two events related to it are when a GHSA is either published or reported. Reported is what the state of a GHSA is when in a "Triage" state (created).
Testing performed in my public testing repo: https://github.com/teodor-yanev/a-testrepo/security/advisories
"Triage" GHSAs can only be created when the 'Private vulnerability reporting' option is enabled, which is why I explicitly stated it in the description.
Also, to avoid confusing users, I added the additional "draft" state not to be considered when initially ingesting GHSAs. This only happens when the profile is created on a repo that already …

Update "no open security advisories rule"

---

profiles/github/artifacts/artifact-signature-extended.yaml
profiles/github/artifacts/artifact-signature-simple.yaml
profiles/github/branch-protection.yaml
profiles/github/dependabot_ghactions.yaml
profiles/github/dependabot_go.yaml
profiles/github/dependabot_npm.yaml
profiles/github/dependabot_npm_docs.yaml
profiles/github/dependabot_pip.yaml
profiles/github/dependencies.yaml
profiles/github/ghas.yaml
profiles/github/homoglyphs.yaml
profiles/github/profile.yaml
profiles/github/repo_security.yaml
profiles/github/stacklok-health-check.yaml
profiles/github/stacklok-profile-remediate.yaml
profiles/github/trivy.yaml
profiles/github/workflow_security.yaml

1. Add display names to our profiles
2. Update the sample Dependabot rule to look at `package.json` in the base (and rename it as such) instead of looking for it in `docs/`. This is more widely applicable than the prior example.
3. The GitHub Actions workflow security profile could benefit from the inclusion of a dependabot rule type for actions
4. The sample remediation profile should not allow actions to update PRs (similar to #78)
5. The dependencies sample profile can make use of dependabot 🎉 
6. Add a repository-configuration-focused sample profile

Some tweaks to sample profiles

---

profiles/github/stacklok-health-check.yaml

According to
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem the right ecosystem is `pip` not `pypi`.
This is very confusing, because the OSV ecosystem is `pypi`.

Fix package_ecosystem for the healthcheck profile

---

rule-types/github/actions_check_pinned_tags.yaml
rule-types/github/codeql_enabled.yaml
rule-types/github/dependabot_configured.yaml
rule-types/github/pr_vulnerability_check.yaml

A bunch of ruletype text updates I found while I was testing different
ruletypes through UI
- more ecosystem examples for the popular dependabot ecosystems
- provide a reasonable default for codeQL schedule
- say that minder will use builtin defaults for the OSV ruletype to make
it clear that the user doesn't have to fill them in
- fix description of exclude for the action pinning ruletype

Minor ruletype descriptions

---

rule-types/github/codeql_enabled.yaml

Our ruletype update validation throws an error if you modify the default
field in any way which is probably incorrect as the default is really
not used except as advisory, but let's not break ruletype apply.
I added the default recently, but luckily the update didn't make it to
the healtcheck yet.

Remove the recently added default

---

rule-types/github/pr_trusty_check.yaml

We recently allowed minder to work with an empty trusty configuration.
This is just a change to the description that allows the UI to give a
hint for the user that they don't have to input anything to the UI box
to make the rule work.

Better description of the ecosystem_config parameter for the UI

---

rule-types/github/actions_check_pinned_tags.yaml

Our example profiles exclude just the action name because that's what frizbee uses internally to exclude:
https://github.com/stacklok/minder-rules-and-profiles/blob/main/profiles/github/stacklok-health-check.yaml#L29
But the rego check in the actions_check_pinned_tags rule was excluding on the full value of uses. This meant that the remediation was always called even if it didn't produce anything and the exclude didn't work.

Exclude the action name only not the full uses in actions_check_pinned_tags

---

rule-types/github/pr_trusty_check.yaml

This option was added to Minder but not to the rule type.

Add the forgotten evaluate_score for the trusty evaluator

---

rule-types/github/codeql_enabled.yaml

Apparently codeQL no longer handles the fact where languages are set but
are not present in the repository and instead errors out.
There is a relatively recent change (Oct-23) to codeQL that is able to
autodetect the languages used:
https://github.blog/changelog/2023-10-23-code-scanning-default-setup-automatically-includes-all-codeql-supported-languages/
and especially:
https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning
says:
"""
If your workflow does not contain a matrix called language, then CodeQL
is configured to run analysis sequentially. If you don't specify
languages in the workflow, CodeQL automatically detects, and attempts to
analyze, any supported languages in the repository.
""" …

Support an empty list of languages in order for codeQL to autodetect them

---

rule-types/github/artifact_signature.yaml

Because the artifact_signature rule uses the deny-by-default model all
we get from the evaluation in case it fails is denied. Especially for
artifacts this is not ideal as we can't tell the user what changed in
the artifact vs. the expected state unless they look at minder logs.
Fixes: #103

Change the artifact_signature rule to use constraints evaluation, not deny-by-default

---

profiles/github/dependabot_rust.yaml

Add a new profile to configure dependabot check for Rust, cargo-based projects.

Add dependabot profile for rust projects

---

rule-types/github/pr_trusty_check.yaml

This PR updates the trusty PR rule to add the new sections for the score components which will be exposed to the evaluator once https://github.com/stacklok/minder/pull/3277 merges.
Note that `evaluate_score` isbeing removed because policies can now be written on all score components, not just one score.

Trusty PR add provenance and activity

---

profiles/github/dependencies.yaml
rule-types/github/pr_trusty_check.yaml

This PR updates the trusty ruletype and the dependencies profile to use the [new configurationfields exposed by recent enhancements to the trusty evaluator](https://github.com/stacklok/minder/pull/3392).
Note that the profile configures the rule to review PRs by default (as opposed to just adding a comment).

Update trusty rule and profile with new fields

---

profiles/github/dependabot_ghactions.yaml
profiles/github/dependabot_go.yaml
profiles/github/dependabot_npm.yaml
profiles/github/dependabot_pip.yaml
profiles/github/dependabot_rust.yaml
profiles/github/dependencies.yaml
profiles/github/ghas.yaml
profiles/github/profile.yaml
profiles/github/repo_security.yaml
profiles/github/trivy.yaml
profiles/github/workflow_security.yaml

Based on feedback, our alerts should not have alerts on by default; disable alerting by default, but allow users to enable it by changing this to "alerts: on".

Profiles should not alert by default

---

rule-types/github/artifact_attestation_slsa.yaml

We didn't keep up with the GH attestations API.
There are two changes:
1) The value of `redicate.buildDefinition.buildType` changed to `https://actions.github.io/buildtypes/workflow/v1`
2) What the runner is (typically that would be `github-hosted`) is now at `buildDefinition.internalParameters.github.runner_environment`
Fixes: #128

Fix the slsa_gh_attestation rule type

---

profiles/github/artifact_attestation_slsa.yaml

We didn't have an example for the GH attestations ruletype which made it
harder to test and discover bugs.

Add an example profile for GH attestations

---

profiles/github/scorecard-action.yaml
rule-types/github/scorecard_enabled.yaml

Basic attempt at writing a scorecard action provision rule and profile

Scorecard action

---

rule-types/github/secret_push_protection.yaml

This option is causing confusion, and it is unlikely that someone would want to set up this rule type to check that secret push protection is disabled.

Remove `enabled` setting from secret_push_protection

---

rule-types/github/actions_check_default_permissions.yaml

I built & presented this rule in a tutorial at CloudNativeSecurityCon: https://cloudnativesecurityconna24.sched.com/event/8470542653b26dbcab395ccc294b81b3
Replaces https://github.com/stacklok/minder-rules-and-profiles/pull/126
Depends on https://github.com/stacklok/minder-smoke-tests/pull/188
Replaces #134

Add rule to detect GitHub Actions using default permissions

---

rule-types/github/artifact_attestation_slsa.yaml

Requiring the repository makes the ruletype not super useful + hard to test

Make repository optional for the GH attestations ruletype

---

rule-types/github/artifact_attestation_slsa.yaml

The following PR removes the skip portion of the ruletype which is set in case the artifact doesn't have any attestations generated. In this case we rather want to fail instead of setting the ruletype evaluation to skipped.
Fixes https://github.com/stacklok/minder/issues/4426

Do not skip, but fail if the artifact doesn't have any slsa attestations generated

---

rule-types/common/license.yaml

This rule type is applicable to other providers, so this moves it to a
common folder to reflect this. It also removes the `provider: github`
setup. Finally, the given branch settings were removed in favor of using
the auto-detected default branch, thus making the rule type mroe
reusable.

Move the `license` rule type to a `common` folder

---

rule-types/github/dockerfile_no_latest_tag.yaml
rule-types/github/no_binaries_in_repo.yaml
rule-types/github/repo_action_allow_list.yaml
rule-types/github/trivy_action_enabled.yaml

This ensures rules are able to leverage the default branch instead of
defaulting to using `main`

Use default branch instead of hardcoding `main`

---

rule-types/github/dockerfile_no_latest_tag.yaml

This reverts commit e91880e04fdfc093e58479259b657814e3b5f497.
The commit broke the rule type accidentally.

Revert "Special-case FROM scratch when detecting the latest tag"

---

rule-types/common/dockerfile_no_latest_tag.yaml

This is also useful for other providers.

Move `docker_no_latest_tag` rule type to common folder

---

rule-types/gitlab/gitlab_protect_branch.yaml
rule-types/gitlab/gitlab_require_merge_requests.yaml

This adds two very basic branch protection rules that we can check for
in Gitlab. One that verifies that branch protection indeed exists and
that it does not allow for "force pushing", and another one that
verifies that merge requests are enforced.

Add branch protection rules for gitlab

---

rule-types/common/license.yaml
rule-types/github/actions_check_default_permissions.yaml
rule-types/github/artifact_attestation_slsa.yaml
rule-types/github/branch_protection_enabled.yaml
rule-types/github/branch_protection_require_pull_requests.yaml
rule-types/github/codeql_enabled.yaml
rule-types/github/dependabot_configured.yaml
rule-types/github/scorecard_enabled.yaml
rule-types/github/secret_push_protection.yaml
rule-types/github/secret_scanning.yaml
rule-types/github/security_insights.yaml
rule-types/github/security_insights_dep_policy.yaml
rule-types/github/security_policy.yaml
rule-types/github/trivy_action_enabled.yaml
rule-types/gitlab/gitlab_dependency_scanning_enabled.yaml
rule-types/gitlab/gitlab_protect_branch.yaml
rule-types/gitlab/gitlab_require_merge_requests.yaml

This displays as the evaluation failure details message in Minder.
Ref https://github.com/stacklok/minder-stories/issues/42

Add evaluation failure message to rego rules

---

rule-types/github/scorecard_enabled.yaml

The `language` property was causing remediation to fail with "generic remediation error status: error".
Removing it since it's not actually used on this rule.

Remove unused property from scorecard_enabled rule

---

rule-types/github/branch_protection_allow_deletions.yaml
rule-types/github/branch_protection_allow_force_pushes.yaml
rule-types/github/branch_protection_allow_fork_syncing.yaml
rule-types/github/branch_protection_enabled.yaml
rule-types/github/branch_protection_enforce_admins.yaml
rule-types/github/branch_protection_lock_branch.yaml
rule-types/github/branch_protection_require_conversation_resolution.yaml
rule-types/github/branch_protection_require_linear_history.yaml
rule-types/github/branch_protection_require_pull_request_approving_review_count.yaml
rule-types/github/branch_protection_require_pull_request_code_owners_review.yaml
rule-types/github/branch_protection_require_pull_request_dismiss_stale_reviews.yaml
rule-types/github/branch_protection_require_pull_request_last_push_approval.yaml
rule-types/github/branch_protection_require_pull_requests.yaml
rule-types/github/branch_protection_require_signatures.yaml
rule-types/github/dependabot_configured.yaml
rule-types/github/security_insights.yaml
rule-types/github/security_insights_dep_policy.yaml
rule-types/github/security_policy.yaml

A number of simplifications to rule configuration, removing required fields that are not actually required, since we have useful defaults.

Update rule configuration

---

rule-types/gitlab/gitlab_dependency_scanning_enabled.yaml
rule-types/gitlab/gitlab_pipeline_secret_detection_enabled.yaml

This adds a new rule that ensures that pipeline secret detection is
enabled. This also updates the dependency scanning template path, since
it'll move to `Jobs`

gitlab: Add new security rule and fix up dependency scanning one

---

profiles/github/ghas.yaml
profiles/github/openssf_security_baseline.yaml
profiles/github/profile.yaml
profiles/github/repo_security.yaml

Sets the default CodeQL schedule to once a week instead of 3x/day, aligning with GitHub's default frequency.

Update CodeQL schedule in sample profiles

---

rule-types/github/workflow_pull_request.yaml

This can be indicative of having a CI/CD pipeline

Add a ruletype that ensures that at least one workflow is triggered by pull_request

---

rule-types/github/workflow_no_pull_request_target.yaml

Adds a ruletype that checks that a workflow does not use the
`pull_request_target` trigger.
Depends on https://github.com/mindersec/minder/pull/4793

Add the workflow_no_pull_request_target rule with tests

---

profiles/github/openssf_scorecard.yaml

One of _my_ goals using Minder is to improve my repository's OpenSSF Scorecard score, since Minder can automatically remediate findings. Minder does not yet have rules to evaluate the full scope of the OpenSSF Scorecard, nor remediate it, but it will still help detect and improve findings.

Introduce an OpenSSF Scorecard profile

---

.github/workflows/update.yaml

Ref: https://github.com/mindersec/minder-rules-and-profiles/actions/runs/11562883909
```
Invalid workflow file: .github/workflows/update.yaml#L7
You have an error in your yaml syntax on line 7
```
Fixes #196

Fix syntax for workflow update testing

---

.github/workflows/update.yaml

The update validation CI job was broken since I had not set the right
branch to check out. By checking out the main branch, we actually do the
validation we needed to do.

Checkout main branch when doing update validation

---

rule-types/github/branch_protection_allow_deletions.yaml
rule-types/github/branch_protection_allow_force_pushes.yaml
rule-types/github/branch_protection_allow_fork_syncing.yaml
rule-types/github/branch_protection_enabled.yaml
rule-types/github/branch_protection_enforce_admins.yaml
rule-types/github/branch_protection_lock_branch.yaml
rule-types/github/branch_protection_require_conversation_resolution.yaml
rule-types/github/branch_protection_require_linear_history.yaml
rule-types/github/branch_protection_require_pull_request_approving_review_count.yaml
rule-types/github/branch_protection_require_pull_request_code_owners_review.yaml
rule-types/github/branch_protection_require_pull_request_dismiss_stale_reviews.yaml
rule-types/github/branch_protection_require_pull_request_last_push_approval.yaml
rule-types/github/branch_protection_require_pull_requests.yaml
rule-types/github/branch_protection_require_signatures.yaml

This makes it so that branch protection rules no longer have a
`required` parameter. Instead, this is replaced by a default value of
`""`

Remove `required` branch from branch protection rules and use default

---

README.md
data-sources/osv.yaml
data-sources/sonatype_oss_index.yaml
rule-types/common/osv_vulnerabilities.yaml
rule-types/common/sonatype_oss_index_vulnerabilities.yaml

These two are samples of how to use data sources in your rule types.

Add data sources and rule types for OSV and Sonatype OSS index

---

data-sources/sonatype-oss-index.yaml

Datasource names are normalized before being passed to REGO, and dashes become underscores.

Fix sonatype datasource name.

---

data-sources/ghapi.yaml
data-sources/osi.yaml

This change adds two data sources useful to implement OSPS Baseline checks.
OSI data source is pretty simple and static, and can be used to verify if a given license is allowed by either OSI or FSF.
GitHub data source is useful to get the license of a given public repository as detected by GitHub. Note that this currently only works for public repositories.

Add OSI and GitHub data sources.

---

.github/workflows/update.yaml
data-sources/ghapi.yaml
data-sources/osi.yaml

Some data sources added recently were missing `context: {}`. Unfortunately, for some reason I haven't looked into yet, this is not a problem locally while it is in SAAS.

Fix context in data sources.

---

rule-types/github/talisman_secrets_scanning.test.yaml
rule-types/github/talisman_secrets_scanning.testdata/correct/.pre-commit-config.yaml
rule-types/github/talisman_secrets_scanning.testdata/misconfigured/.pre-commit-config.yaml
rule-types/github/talisman_secrets_scanning.yaml

Talisman pre-commit hook secrets scanning

---

.github/workflows/trivy.yml

This is just a testing tool, we don't wanna be carrying weird vulns on
testing code, but this also isn't shipped anywhere.

Only warn on critical issues for trivy

---

rule-types/github/source_code_is_public.yaml

This rule type checks that the repository is publicly available. This is straightforward to check on GitHub since every repo has a static URL, so we just check that the repository is public.
This can be used to implement `OSPS-QA-01`.

Add `source_code_is_public` rule type.

---

data-sources/spdx.yaml
rule-types/github/permissive_license.yaml

This rule type checks that the license detected by GitHub is approved by either OSI or FSF. It uses two data sources, one to call GitHub API to get the SPDX identifier of the license, and another one to get the updated list of licenses approved by from SPDX repository.
This rule can be used to implement `OSPS-LE-02`.
P.S.: the name is ugly, please advise. 😅

Add `permissive_license` rule type.

---

.github/workflows/trivy.yml

This way it will not check for our test data.

Add `skip-dirs` configuration for trivy

---

data-sources/openssf_bestpractices.yaml
profiles/github/openssf_scorecard.yaml
rule-types/github/openssf_bestpractices.yaml

Add a rule that ensures that the project has an OpenSSF Best Practices badge at the specified level (defaulting to: "passing"). This is driven by the OpenSSF Best Practices data source, which queries bestpractices.dev.
Add the new rule type to the OpenSSF Scorecard profile.

Introduce OpenSSF Best Practices Badge rule

---

rule-types/github/grype_github_action_scan_container_image.test.yaml
rule-types/github/grype_github_action_scan_container_image.testdata/action_enabled/.github/workflows/wf.yml
rule-types/github/grype_github_action_scan_container_image.testdata/action_enabled_not_for_container_image_scanning/.github/workflows/wf.yml
rule-types/github/grype_github_action_scan_container_image.testdata/action_missing/.github/workflows/wf.yml
rule-types/github/grype_github_action_scan_container_image.yaml
rule-types/github/grype_github_action_scan_repo.test.yaml
rule-types/github/grype_github_action_scan_repo.testdata/action_enabled/.github/workflows/wf.yml
rule-types/github/grype_github_action_scan_repo.testdata/action_enabled_not_for_repo_scanning/.github/workflows/wf.yml
rule-types/github/grype_github_action_scan_repo.testdata/action_missing/.github/workflows/wf.yml
rule-types/github/grype_github_action_scan_repo.yaml

This ensures that folks do container or repo scanning and uses the
Grype tool for the job

Add rule types to check for Anchore's `scan-action` which calls grype

---

security-baseline/data-sources/ghapi.yaml
security-baseline/rule-types/github/osps-vm-05.yaml

Add a check for OSPS-VM-05: contacts and process for vuln reporting are published.
No unit tests because they don't support data sources yet, as fas as I know.

Add a check for OSPS-VM-05: contacts and process for vuln reporting

---

security-baseline/profiles/security-baseline-level-1.yaml
security-baseline/rule-types/github/osps-ac-02.test.yaml
security-baseline/rule-types/github/osps-ac-02.yaml
security-baseline/rule-types/github/osps-br-03.test.yaml
security-baseline/rule-types/github/osps-br-03.yaml
security-baseline/rule-types/github/osps-qa-01.test.yaml
security-baseline/rule-types/github/osps-qa-01.yaml

We completed VM-05 but didn't link it in.  This adds BR-03 and AC-02 (handled trivially by GitHub) as well.  Still missing:
* AC-01: this needs the organization object (and possibly GitHub App permission changes)
* BR-09: this needs writing, it depends on the release object (some testing needed)
* LE-04: I think this is in progress, so I didn't do it.
From discussion on https://github.com/ossf/security-baseline/pulls, it looks like there will be the following changes:
* Move BR-10 up one level: https://github.com/ossf/security-baseline/pull/162
* Add DO-03 (https://github.com/mindersec/minder-rules-and-profiles/pull/232) and DO-05 (I will have a PR shortly) to level 1
Move DO-13 and SA-02 to level 2.
https://github.com/ossf/security-baseline/pull/162
* Rewriting QA-03 to target having a …

Fill out half of remaining ruletypes in policy for level 1

---

security-baseline/profiles/security-baseline-level-1.yaml

Following the updates to https://baseline.openssf.org/#level-1
- Remove OSPS-BR-10 from level 1
- Remove OSPS-DO-1 from level 1
- Remove OSPS-SA-02 from level 1
- Add placeholder for OSPS-DO-03 in level 1
- Add placeholder for OSPS-DO-05 in level 1

Update security baseline level 1 profile

---

security-baseline/profiles/security-baseline-level-1.yaml
security-baseline/rule-types/github/osps-br-09.test.yaml
security-baseline/rule-types/github/osps-br-09.testdata/all-https.json
security-baseline/rule-types/github/osps-br-09.testdata/download-url-not-https.json
security-baseline/rule-types/github/osps-br-09.testdata/url-not-https.json
security-baseline/rule-types/github/osps-br-09.yaml

Check that the assets that are part of a release have an HTTPS URL and download URL. This should always be the case with GitHub releases.

Add ruletype for OSPS-BR-09

---

security-baseline/profiles/security-baseline-level-1.yaml
security-baseline/rule-types/github/osps-do-05.test.yaml
security-baseline/rule-types/github/osps-do-05.yaml

Add an implementation for [OSPS-DO-05](https://baseline.openssf.org/#osps-do-05):
> It is recommended that projects use their VCS default issue tracker. If an extarnal source is used, ensure that the project documentation and contributing guide clearly and visibly explain how to use the reporting system.
>
> It is recommended that project documentation also sets expectations for how defects will be triaged and resolved.
Fixes #288

Add OSPS-DO-05 rule

---

security-baseline/rule-types/github/osps-br-01.yaml

```
$ minder ruletype apply -f security-baseline/rule-types/github/osps-br-01.yaml
No config file present, using default values.
Message: error applying rule type from security-baseline/rule-types/github/osps-br-01.yaml
Details: error creating rule type from security-baseline/rule-types/github/osps-br-01.yaml: rpc error: code = InvalidArgument desc = Validation failed:
- Field 'rule_type.description': value length must be at most 1000 characters
```

Shorten the description of BR-01 to fit in <1000 chars

---

security-baseline/rule-types/github/osps-qa-03.test.yaml
security-baseline/rule-types/github/osps-qa-03.testdata/gemfile_no_lock/Gemfile
security-baseline/rule-types/github/osps-qa-03.testdata/gemfile_with_lock/Gemfile
security-baseline/rule-types/github/osps-qa-03.testdata/gemfile_with_lock/Gemfile.lock
security-baseline/rule-types/github/osps-qa-03.testdata/go_mod_no_go_sum/go.mod
security-baseline/rule-types/github/osps-qa-03.testdata/go_mod_with_go_sum/go.mod
security-baseline/rule-types/github/osps-qa-03.testdata/go_mod_with_go_sum/go.sum
security-baseline/rule-types/github/osps-qa-03.testdata/package_json_no_lock/package.json
security-baseline/rule-types/github/osps-qa-03.testdata/package_json_with_package_lock/package-lock.json
security-baseline/rule-types/github/osps-qa-03.testdata/package_json_with_package_lock/package.json
security-baseline/rule-types/github/osps-qa-03.testdata/package_json_with_yarn_lock/package.json
security-baseline/rule-types/github/osps-qa-03.testdata/package_json_with_yarn_lock/yarn.lock
security-baseline/rule-types/github/osps-qa-03.yaml

Fix #289
I intentionally didn't add it to the profile because the definition isn't final.

Add ruletype for OSPS-QA-03
