profiles/github/stacklok-profile-read-only.yaml, profiles/github/stacklok-profile-remediate.yaml
This allows us to enable more actions in stagign
=> Enable PR reviews for actions

rule-types/github/actions_check_pinned_tags.yaml
Depends on https://github.com/stacklok/minder/pull/1808
=> Add a remediation to the actions_check_pinned_tags rule_type

profiles/github/trivy.yaml
This adds a very simple profile that simply contains the
`trivy_action_enabled` rule
=> Create simple profile for trivy

rule-types/github/trivy_action_enabled.yaml
This creates a dedicated workflow that will run trivy on a repository.
=> Add remediation to rule that checks trivy

profiles/github/stacklok-profile-remediate.yaml
Let's take the new features into account
=> Extend the minder checks for minder/server

rule-types/github/dependabot_configured.yaml
This makes it easier to use and fix.
=> Don't check interval for dependabot rule type

.github/workflows/lint.yaml
=> Add CI job to lint rule types

rule-types/github/codeql_enabled.yaml
=> Remove explicit branch setup in CodeQL rule

rule-types/github/trivy_action_enabled.yaml
Fixes https://github.com/stacklok/epics/issues/275
=> Fix the Trivy ruletype causing an error when remediation is enabled

profiles/github/stacklok-health-check.yaml
Update the names in the health check profile to be more descriptive.
=> Update the names in the health check profile

rule-types/github/pr_trusty_check.yaml
Found when working on the docs
=> Trusty supports Go

rule-types/github/default_workflow_permissions.yaml
=> Add remediation for default_workflow_permissions

rule-types/github/secret_push_protection.yaml
This reverts commit faf206019231bcf1e9ede1251f92c974c2134b09.
=> Revert "Remove `enabled` setting from secret_push_protection (#132)"

profiles/github/openssf_security_baseline.yaml, rule-types/github/security_policy.yaml
This applies the suggestions from #136, which I merged because @puerco will be out for the next two weeks.
=> Apply suggestions from #136

rule-types/github/branch_protection_enabled.yaml
The following PR enables the remediation tests for branch_protection_enabled.
=> Enable remediation tests for branch_protection_enabled

rule-types/github/actions_check_pinned_tags.yaml, rule-types/github/branch_protection_allow_deletions.yaml, rule-types/github/branch_protection_allow_force_pushes.yaml, rule-types/github/branch_protection_allow_fork_syncing.yaml, rule-types/github/branch_protection_enabled.yaml, rule-types/github/branch_protection_enforce_admins.yaml, rule-types/github/branch_protection_lock_branch.yaml, rule-types/github/branch_protection_require_conversation_resolution.yaml, rule-types/github/branch_protection_require_linear_history.yaml, rule-types/github/branch_protection_require_pull_request_approving_review_count.yaml, rule-types/github/branch_protection_require_pull_request_code_owners_review.yaml, rule-types/github/branch_protection_require_pull_request_dismiss_stale_reviews.yaml, rule-types/github/branch_protection_require_pull_request_last_push_approval.yaml, rule-types/github/branch_protection_require_pull_requests.yaml, rule-types/github/branch_protection_require_signatures.yaml, rule-types/github/codeql_enabled.yaml, rule-types/github/dependabot_configured.yaml, rule-types/github/invisible_characters_check.yaml, rule-types/github/license.yaml, rule-types/github/mixed_scripts_check.yaml, rule-types/github/no_binaries_in_repo.yaml, rule-types/github/no_open_security_advisories.yaml, rule-types/github/scorecard_enabled.yaml, rule-types/github/secret_push_protection.yaml, rule-types/github/secret_scanning.yaml, rule-types/github/trivy_action_enabled.yaml
The following PR sets the correct release_phase fields for all ruletypes based on the ruletype assessment we did.
Fixes #143
=> Set the correct release_phase fields for all ruletypes

rule-types/github/artifact_attestation_slsa.yaml, rule-types/github/branch_protection_lock_branch.yaml, rule-types/github/codeql_enabled.yaml, rule-types/github/invisible_characters_check.yaml, rule-types/github/repo_action_allow_list.yaml
Addressing a few small changes that were missed out.
=> Fix a few typos and update the release phase for one of the ruletypes

profiles/github/branch-protection.yaml, profiles/github/ghas.yaml, profiles/github/openssf_security_baseline.yaml, profiles/github/profile.yaml, profiles/github/repo_security.yaml, profiles/github/stacklok-health-check.yaml, profiles/github/stacklok-profile-remediate.yaml, rule-types/github/automatic_branch_deletion.yaml, rule-types/github/branch_protection_allow_deletions.yaml, rule-types/github/branch_protection_allow_force_pushes.yaml, rule-types/github/branch_protection_require_signatures.yaml, rule-types/github/secret_push_protection.yaml, rule-types/github/secret_scanning.yaml
=> Remove enabled property from ruletypes

rule-types/gitlab/gitlab_dependency_scanning_enabled.yaml
=> gitlab: Create rule to check for dependency scanning being enabled.

profiles/gitlab/gitlab_auto_devops.yaml, profiles/gitlab/profile.yaml
=> Add sample profiles for GitLab

rule-types/github/branch_protection_allow_deletions.yaml, rule-types/github/branch_protection_allow_force_pushes.yaml, rule-types/github/branch_protection_allow_fork_syncing.yaml, rule-types/github/branch_protection_enabled.yaml, rule-types/github/branch_protection_enforce_admins.yaml, rule-types/github/branch_protection_lock_branch.yaml, rule-types/github/branch_protection_require_conversation_resolution.yaml, rule-types/github/branch_protection_require_linear_history.yaml, rule-types/github/branch_protection_require_pull_request_approving_review_count.yaml, rule-types/github/branch_protection_require_pull_request_code_owners_review.yaml, rule-types/github/branch_protection_require_pull_request_dismiss_stale_reviews.yaml, rule-types/github/branch_protection_require_pull_request_last_push_approval.yaml, rule-types/github/branch_protection_require_pull_requests.yaml, rule-types/github/branch_protection_require_signatures.yaml, rule-types/github/dependabot_configured.yaml, rule-types/github/security_insights.yaml, rule-types/github/security_insights_dep_policy.yaml, rule-types/github/security_policy.yaml
This reverts commit 668f0105b95e220e066325340e903e9734eaeb4c.
The commit breaks minder unit tests
=> Revert "Update rule configuration (#179)"

.github/workflows/lint.yaml
=> Use mindersec for lint job as opposed to the previous org

.github/workflows/update.yaml
This creates a workflow that ensures that an upgrade of a rule type would work.
=> Add update testing

data-sources/security-insights.yaml
This commit adds an experimental security insights data source to the repository.
=> Add Security Insights data source

CONTRIBUTING.md, README.md
The following PR updates the README file adding more information regarding what are rules and profiles and how one can get started writing ones.
Fixes https://github.com/mindersec/minder-rules-and-profiles/issues/223
=> Update the README with information about creating rules and profiles

rules_test.go
=> Enable rego printing in tests

rule-types/github/golangci-lint_github_action.test.yaml, rule-types/github/golangci-lint_github_action.testdata/repo_with_golangci-lint_gh_action/.github/workflows/positive_mock.yml, rule-types/github/golangci-lint_github_action.testdata/repo_without_golangci-lint_gh_action/.github/workflows/negative_mock.yml, rule-types/github/golangci-lint_github_action.yaml
Adds a new Rule Type to verify that golangci-lint github action is configured.
=> New rule def for golangci-lint github action

profiles/github/security_baseline_1.yaml
Fixes https://github.com/stacklok/minder-stories/issues/194
=> Add baseline 1 profile

security-baseline/data-sources/spdx.yaml
=> Add spdx to security baseline data sources

profiles/github/dependencies.yaml, profiles/github/stacklok-profile-remediate.yaml
The following PR reflects the latest changes to the Stacklok-related profiles. I suppose we might want to remove these from here in the future.
=> Reflect the latest stacklok profile changes
